In [1]:
#This is a Comment
print "Hello World"

Hello World


In [4]:
a = 4
print(a)

4


Go to cell and select cell type and select markdown for just text display and not code

Working with Arrays 

In [5]:
import numpy as np

In [6]:
my_List = [1,2,3,4,5]

In [7]:
my_Array = np.array(my_List)

In [22]:
print("my array data is : %s" %my_Array)
print("Minimum of the Array is : %s" % min(my_Array))
print("Maximum of the Array is : %s" %max(my_Array))

my array data is : [1 2 3 4 5]
Minimum of the Array is : 1
Maximum of the Array is : 5


Creating a array with all elements as '0'

In [26]:
zero_array = np.zeros(10)
print(zero_array,zero_array.dtype)

(array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), dtype('float64'))


In [30]:
array_of_ones = np.ones([5,5])
array_of_ones

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [31]:
np.eye(5)


array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [32]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

Using Scalars

In [35]:
# Used for division else the result is a round of the value
from __future__ import division
5/2

2.5